"""CVE router package.

Split from `routers.cves` (F1.2) without changing route registration order or
handler behavior.

Copyright © 2026 Sai Harsha Vardhan
SPDX-License-Identifier: BUSL-1.1
"""

from .changes import cve_changes, changes_router
from .common import _row_to_cve_dict, row_to_cve_dict
from .detail import (
    _build_cve_drawer_bundle,
    _circl_enrichment_patch,
    _detail_enrich_circl,
    _detail_enrich_exploits,
    _detail_enrich_osv,
    _detail_enrich_otx,
    _drawer_related_payload,
    _drawer_sentences_payload,
    _load_cve_detail_from_db,
    detail_router,
    enrich_cve_circl,
    get_cve,
    get_cve_drawer_bundle,
    get_cve_epss_history,
    get_cve_related,
    get_cve_sentences,
    load_otx_pulses_for_cve,
    load_public_exploits_for_cve,
)
from .intel import intel_router
from .list import (
    CVE_KEYSET_ORDER_BY,
    CVE_ORDER_BY,
    CVE_SELECT,
    _build_cve_filters,
    _cve_count_cache_key,
    _decode_feed_cursor,
    _encode_feed_cursor,
    _framework_match_clause,
    _is_cve_id,
    _parse_framework_list,
    _sort_by_stack_relevance,
    _stack_match_clause,
    _stack_relevance_sql,
    _text_match_or_clause,
    _timeline_date_key,
    _validate_published_on,
    export_cves,
    list_cves,
    list_router,
    match_cves_to_assets,
    stats,
    stats_timeline,
    stats_top_vendors,
    top_techniques,
)
from .models import (
    AssetMatchItem,
    AssetMatchRequest,
    CorrelationFeedbackBody,
    CorrelationSuppressBody,
    RiskScoreRequest,
)

__all__ = [
    "changes_router",
    "list_router",
    "detail_router",
    "intel_router",
    "AssetMatchItem",
    "AssetMatchRequest",
    "CorrelationFeedbackBody",
    "CorrelationSuppressBody",
    "RiskScoreRequest",
    "CVE_KEYSET_ORDER_BY",
    "CVE_ORDER_BY",
    "CVE_SELECT",
    "_build_cve_drawer_bundle",
    "_build_cve_filters",
    "_circl_enrichment_patch",
    "_cve_count_cache_key",
    "_decode_feed_cursor",
    "_detail_enrich_circl",
    "_detail_enrich_exploits",
    "_detail_enrich_osv",
    "_detail_enrich_otx",
    "_drawer_related_payload",
    "_drawer_sentences_payload",
    "_encode_feed_cursor",
    "_framework_match_clause",
    "_is_cve_id",
    "_load_cve_detail_from_db",
    "_parse_framework_list",
    "_row_to_cve_dict",
    "_sort_by_stack_relevance",
    "_stack_match_clause",
    "_stack_relevance_sql",
    "_text_match_or_clause",
    "_timeline_date_key",
    "_validate_published_on",
    "cve_changes",
    "enrich_cve_circl",
    "export_cves",
    "get_cve",
    "get_cve_drawer_bundle",
    "get_cve_epss_history",
    "get_cve_related",
    "get_cve_sentences",
    "list_cves",
    "load_otx_pulses_for_cve",
    "load_public_exploits_for_cve",
    "match_cves_to_assets",
    "row_to_cve_dict",
    "stats",
    "stats_timeline",
    "stats_top_vendors",
    "top_techniques",
]
