"""Interview preparation Q&A data for BRIEFR study guide."""

from __future__ import annotations

TOC_LINKS: list[tuple[str, str]] = [
    [
        "iv-part.html",
        "How to use this section"
    ],
    [
        "iv-architecture.html",
        "1 \u00b7 Architecture & system design"
    ],
    [
        "iv-security.html",
        "2 \u00b7 Security & trust boundaries"
    ],
    [
        "iv-backend-db.html",
        "3 \u00b7 Backend & database"
    ],
    [
        "iv-ingest-scheduler.html",
        "4 \u00b7 Ingest & scheduler"
    ],
    [
        "iv-correlation-scoring.html",
        "5 \u00b7 Correlation & scoring"
    ],
    [
        "iv-ml-embeddings.html",
        "6 \u00b7 ML & embeddings"
    ],
    [
        "iv-detection-forge.html",
        "7 \u00b7 Detection & Forge"
    ],
    [
        "iv-frontend-ux.html",
        "8 \u00b7 Frontend & UX"
    ],
    [
        "iv-api-ops.html",
        "9 \u00b7 API & operations"
    ],
    [
        "iv-devops-deploy.html",
        "10 \u00b7 DevOps & deploy"
    ],
    [
        "iv-product-behavioral.html",
        "11 \u00b7 Product, behavioral & solo owner"
    ]
]

SEGMENTS: list[dict] = [
    {
        "slug": "iv-part",
        "page_id": "iv-part",
        "chapter_num": "Interview \u00b7 Intro",
        "title": "How to use interview prep",
        "dek": "Orientation for technical and behavioral interview loops on BRIEFR.",
        "prev": ("roadmap-future.html", "What's next & open gaps"),
        "next": ("iv-architecture.html", "Architecture & system design"),
        "body_html": "        <p>This section helps you explain BRIEFR in interviews\u2014system design, security boundaries, ingest, scoring, and how you would operate it in production. Each chapter is Q&amp;A format grouped by category (what it does, implementation, integration, failure modes, performance, security, tradeoffs) per issue <a href=\"https://github.com/Soldier0x0/briefr/issues/498\">#498</a>.</p>\n        <p><strong>How to use it:</strong> Skim a chapter before a loop. For architecture rounds, chain layers (ingest \u2192 Postgres \u2192 API \u2192 UI). For behavioral rounds, use the solo-owner chapter in first person. Cross-check claims against <code>docs/PRODUCT_STATUS.md</code>\u2014it wins when this guide lags.</p>\n        <p><strong>Conventions:</strong> Answers cite real flags, jobs, and modules. Minimum depth is one concrete BRIEFR example per answer, not generic CVE-platform hand-waving.</p>",
        "questions": [
        ],
    },
    {
        "slug": "iv-architecture",
        "page_id": "iv-architecture",
        "chapter_num": "Interview \u00b7 1",
        "title": "Architecture & system design",
        "dek": "Monolith boundaries, asyncio, single-worker defaults, and request vs background work.",
        "prev": ("iv-part.html", "How to use interview prep"),
        "next": ("iv-security.html", "Security & trust boundaries"),
        "questions": [
            {"q": "What is BRIEFR at a high level?", "a": "BRIEFR is a self-hosted CVE intelligence and detection-engineering platform. It ingests NVD, KEV, EPSS, and enrichment feeds into PostgreSQL, scores and correlates them server-side, and exposes everything through a React analyst UI with Forge detection workflows and an operator Admin console."},
            {"q": "Describe the four-layer architecture.", "a": "The pipeline is Feed Ingestion (APScheduler jobs in <code>scheduler.py</code>) \u2192 PostgreSQL (asyncpg pool) \u2192 FastAPI API (<code>main.py</code> + routers) \u2192 React UI (<code>frontend/src</code>). Heavy work never runs on the HTTP request path; schedulers and background jobs own sync, correlation, and ML."},
            {"q": "Why is BRIEFR a monolith rather than microservices?", "a": "A single deployable unit matches the solo-operator and small-team audience: one Postgres, one uvicorn process, one scheduler owner. Cross-cutting concerns\u2014auth, rate limits, metering, and job locks\u2014stay coherent without distributed tracing overhead. Scale-out is optional via API-only workers plus a shared rate-limit store."},
            {"q": "Why does BRIEFR run a single uvicorn worker by design?", "a": "Default rate-limit token buckets are in-process. Multiple workers would split buckets unless <code>BRIEFR_RATE_LIMIT_STORE=db</code> persists them in <code>sync_state</code>. The documented production pattern is one API worker plus one scheduler owner, not an arbitrary worker fleet."},
            {"q": "How does asyncio fit into the backend?", "a": "FastAPI handlers are <code>async def</code>; database I/O uses asyncpg. Scheduled jobs are async coroutines registered with APScheduler. The outbound <code>api_queue</code> serializes external HTTP per source so NVD pacing and circuit breakers stay predictable under concurrent requests."},
            {"q": "What is the role of <code>main.py</code> lifespan?", "a": "Lifespan opens the asyncpg pool, optionally starts APScheduler when <code>BRIEFR_SCHEDULER_ENABLED=1</code>, may start an in-process Procrastinate worker when enabled, runs startup hygiene (session cleanup, integrity probes), and shuts everything down cleanly on exit."},
            {"q": "How do analyst and admin surfaces split?", "a": "Analyst routes live under the main shell (BRIEF, FEED, IOC, Incidents, Forge) behind session auth. Admin is a separate sidebar shell with operator tools: scheduler, feed health, backups, config, AI operations, and security posture. Both share the same FastAPI app and Postgres backend."},
            {"q": "What is the DetailDrawer and why is it central?", "a": "The DetailDrawer is the CVE deep-dive overlay: Overview (OP/Threat/Env), Intel, Detect, Related, and more. A drawer bundle endpoint assembles sub-resources in parallel, each on its own DB connection, so asyncpg concurrency stays safe while the UI renders quickly."},
            {"q": "How does BRIEFR handle optional external API keys?", "a": "No keys are required for core CVE feed, search, and RSS. IOC enrichment (VirusTotal, AbuseIPDB, GreyNoise) and LLM PDF summaries stay empty until operators add keys. Process environment wins over <code>backend/.env</code> because <code>load_dotenv()</code> does not override existing env vars."},
            {"q": "What is the outbound API queue?", "a": "<code>api_queue</code> serializes outbound calls to rate-limited sources (NVD, OTX, LLM providers). <code>/api/health</code> exposes per-source queue depth so operators see waiting vs active work. Feed sync paths pass human-readable <code>operation</code> labels for the header Background sync indicator."},
            {"q": "How does the platform separate read and write paths?", "a": "Analyst GET endpoints read from Postgres and caches (<code>feed_cache</code>, <code>ioc_cache</code>). Writes flow through ingest jobs, admin config apply, or authenticated POST/PATCH routes. NVD ingest uses explicit transaction boundaries so slow enrichments cannot hold writer connections."},
            {"q": "What is Procrastinate's role relative to APScheduler?", "a": "APScheduler remains the in-process cron owner for ~27 recurring jobs. Procrastinate (optional, <code>PROCRASTINATE_ENABLED</code>) adds durable outbound jobs\u2014health ping, stack backfill, LLM product extraction\u2014with Postgres-backed retries. Most ingest still runs through APScheduler locks."},
            {"q": "How does multi-worker deployment work if needed?", "a": "Run multiple uvicorn replicas with <code>BRIEFR_SCHEDULER_ENABLED=0</code> on API-only nodes and exactly one scheduler owner. Set <code>BRIEFR_RATE_LIMIT_STORE=db</code> so auth, refresh, and IOC limits are shared. APScheduler must not run on every replica or jobs would duplicate."},
            {"q": "What frontend build stack is used?", "a": "React 19 with Vite, React Router 7, plain JSX/CSS with semantic design tokens\u2014no Tailwind runtime. Chart.js was removed; charts use Recharts behind <code>ChartShell</code>. Radix primitives provide accessible dialogs, selects, and menus styled with BRIEFR tokens."},
            {"q": "How is state preserved across tab switches?", "a": "Main analyst tabs use <code>hidden</code> panels instead of unmounting so FEED scroll position and filters survive. DetailDrawer Intel/Detect/Related tabs stay mounted after first visit for the same reason. URL query params (<code>?tab=</code>, <code>?cve=</code>) sync navigation for back-button behavior."},
            {"q": "What is the wallboard and how does it differ from the analyst UI?", "a": "Wallboard v2 is a kiosk-oriented, mono-styled tile grid for SOC displays. It authenticates via <code>X-BRIEFR-Wallboard-Token</code> header (or admin-configured token), not the analyst session cookie. Top-risk tiles rank by Operational Priority then Threat Score."},
            {"q": "How does BRIEFR document architectural truth?", "a": "<code>docs/PRODUCT_STATUS.md</code> is the living runtime truth; <code>docs/SYSTEM_DESIGN.md</code> describes structure. When docs disagree with code, code and PRODUCT_STATUS win. The maintainer-export study guide and graphify knowledge graph support onboarding."},
            {"q": "What are intentional non-goals in the current architecture?", "a": "Full multi-tenant SaaS, a shipped all-in-one docker-compose platform (Postgres compose exists), STIX export in the current loop, and heavy ML on the request path. Detection composer beyond deterministic templates remains parked; the product optimizes analyst time on a single server."},
            {"q": "How would you diagram BRIEFR for an interviewer?", "a": "Draw external feeds on the left, APScheduler ingest jobs writing Postgres in the middle, FastAPI serving JSON to React on the right, and call out the scheduler owner + single-worker default. Mention session-gated <code>/api/*</code>, job locks, and that correlation/scoring are server-side\u2014not recomputed in the browser."},
            {"q": "What is the request-path vs background-work rule?", "a": "ML, enrichment sweeps, and external syncs belong in <code>scheduler.py</code> jobs. Request handlers do DB reads and cached lookups only. Violating this exhausts pools and couples analyst latency to NVD/LLM outages\u2014danger zone #6."},
            {"q": "How does ORJSON fit the API layer?", "a": "FastAPI default response class uses ORJSON for faster serialization on large CVE list payloads. It is an implementation detail behind routers\u2014clients still see standard JSON."},
            {"q": "What is the graphify knowledge graph used for?", "a": "AST-derived <code>graphify-out/</code> maps modules, jobs, and inferred edges for onboarding. Agents run <code>graphify query</code> before broad code exploration; after code edits, <code>graphify update .</code> keeps the graph current."},
        ],
    },
    {
        "slug": "iv-security",
        "page_id": "iv-security",
        "chapter_num": "Interview \u00b7 2",
        "title": "Security & trust boundaries",
        "dek": "Sessions, JWT refresh, rate limits, secrets, and fail-closed production posture.",
        "prev": ("iv-architecture.html", "Architecture & system design"),
        "next": ("iv-backend-db.html", "Backend & database"),
        "questions": [
            {"q": "What are BRIEFR's two independent auth layers?", "a": "Optional edge auth: Cloudflare Tunnel + Zero Trust email OTP protects the public hostname\u2014outside FastAPI. Application auth: username/password with server-side sessions (<code>briefr_at</code> cookie), JWT access tokens, and refresh rotation. Operators can use either or both; they do not replace each other."},
            {"q": "How does session authentication work?", "a": "First-run <code>/api/auth/setup</code> creates the admin user. Login issues a short-lived access token and refresh token stored in HttpOnly cookies. Analyst <code>/api/*</code> routes require a valid session via middleware; admin routes additionally require the <code>admin</code> role with live <code>is_active</code> revalidation."},
            {"q": "Explain JWT + refresh token flow.", "a": "Access tokens authorize API calls; refresh tokens rotate on <code>POST /api/auth/refresh</code>. Concurrent 401s dedupe through a shared in-flight <code>refreshAccessToken()</code> in <code>api.js</code> so one refresh does not stampede and revoke all sessions. Password change revokes every active session immediately."},
            {"q": "What happened to the legacy admin API key?", "a": "Sprint A0 removed <code>BRIEFR_ADMIN_API_KEY</code> because it failed open when unset. Admin operations now require a logged-in user with the admin role. Production fails closed without <code>JWT_SECRET</code>\u2014no silent dev auto-generation in production posture."},
            {"q": "How are rate limits implemented?", "a": "Token-bucket limiters guard auth, refresh, IOC lookup, and admin endpoints. Enable with <code>RATE_LIMIT_ENABLED=1</code> in production. Buckets default in-memory; <code>BRIEFR_RATE_LIMIT_STORE=db</code> persists them in <code>sync_state</code> for multi-worker deployments."},
            {"q": "What SSRF protections exist?", "a": "Outbound fetches block CGNAT range <code>100.64.0.0/10</code> and other unsafe targets. Refresh endpoints reject sessions past <code>expires_at</code>. LLM summary routes require authenticated sessions\u2014no anonymous PDF summarization that could proxy arbitrary URLs."},
            {"q": "How are secrets handled at rest?", "a": "Secret-typed admin config keys encrypt in <code>app_settings</code> when <code>BRIEFR_SETTINGS_KEY</code> is set (ADR-006). Without it, secrets stay in process env or <code>.env</code> only. Structured logging redacts <code>*_KEY</code>, <code>*_TOKEN</code>, <code>*_SECRET</code>, and <code>*_PASSWORD</code> in extra fields\u2014never log raw secrets in message strings."},
            {"q": "What is the wallboard trust boundary?", "a": "Wallboard uses a dedicated header token, not the analyst session. Query-string <code>?token=</code> was removed (Sprint A7). Optional <code>WALLBOARD_TOKEN</code> in admin config can gate kiosk mode. Tokenless wallboard in production triggers posture warnings."},
            {"q": "How does BRIEFR fail closed in production?", "a": "Startup logs warnings for unsafe flags: rate limits off, insecure cookies, tokenless wallboard when <code>BRIEFR_ENV=production</code>. The Security admin panel mirrors the same checks. Missing <code>JWT_SECRET</code> blocks production boot rather than generating an ephemeral secret."},
            {"q": "What audit trail exists for operator actions?", "a": "<code>audit_log</code> records admin mutations with redacted targets via <code>redact.py</code>. DB explorer browse events log without row bodies. Webhook and config changes are traceable. Retention cleanup ages audit rows on a conservative 365-day window."},
            {"q": "How is role revalidation enforced?", "a": "JWT role claims are not trusted blindly\u2014handlers re-check <code>users.is_active</code> and role on sensitive routes (#392). Deactivated users lose access immediately even if an old access token has not expired."},
            {"q": "What CORS and origin controls exist?", "a": "<code>ALLOWED_ORIGINS</code> binds at middleware startup; changing it requires restart (honest <code>apply_strategy: restart</code> in config schema). Self-hosted deployments typically front nginx on one origin; dev uses Vite proxy to <code>/api</code>."},
            {"q": "How are webhook destinations secured?", "a": "Admin CRUD for webhook destinations stores configs masked on GET. Delivery dedupe is per destination. Test webhooks work even on disabled destinations for validation. Delivery log errors are masked on read."},
            {"q": "What protects the admin DB explorer?", "a": "Allowlisted tables only\u2014deny by default. Sensitive tables (<code>users</code>, <code>sessions</code>, <code>webhook_destinations</code>) return 404. <code>cves</code> requires a <code>cve_id</code> filter. Rate limit 30/min; browse is audited without returning full row payloads in logs."},
            {"q": "How does LLM outbound data minimization work?", "a": "<code>ai/llm_payload.py</code> skips provider HTTP when messages or source text are empty\u2014no quota burn on blanks. Prompt text is not stored in <code>ai_operations</code>; only redacted metadata and token counts. Admin can view captured payloads for failed ops when recorded."},
            {"q": "What network egress assumptions should operators know?", "a": "The app initiates outbound HTTPS to NVD, threat feeds, and optional IOC/LLM APIs. Inbound is typically nginx \u2192 uvicorn on localhost. No inbound agent protocol\u2014it's a pull-based intel dashboard, not an EDR."},
            {"q": "How are refresh-token reuse attacks handled?", "a": "Refresh rotation with reuse detection can revoke all sessions if the same refresh token is presented twice. Frontend dedupes concurrent refresh calls to avoid accidental self-revocation under parallel 401 retries."},
            {"q": "What is the trust model for correlation and scoring output?", "a": "Scores are computed server-side from auditable inputs (KEV, CVSS, EPSS, stack terms). Correlation lanes expose explainable factors\u2014not opaque ML black boxes for OP/Threat. ML augments optional detection context and embeddings retrieval, not the primary risk band."},
            {"q": "How would you harden a fresh BRIEFR install?", "a": "Set <code>JWT_SECRET</code>, enable <code>RATE_LIMIT_ENABLED=1</code>, use <code>AUTH_COOKIE_SECURE=1</code> behind TLS, configure <code>BRIEFR_SETTINGS_KEY</code> for DB-stored secrets, rotate wallboard token, and optionally add Cloudflare Zero Trust at the edge."},
        ],
    },
    {
        "slug": "iv-backend-db",
        "page_id": "iv-backend-db",
        "chapter_num": "Interview \u00b7 3",
        "title": "Backend & database",
        "dek": "asyncpg, Alembic, Postgres production path, SQLite test fallback, and data model.",
        "prev": ("iv-security.html", "Security & trust boundaries"),
        "next": ("iv-ingest-scheduler.html", "Ingest & scheduler"),
        "questions": [
            {"q": "Why PostgreSQL in production?", "a": "Production requires Postgres 16 with asyncpg pooling (<code>BRIEFR_REQUIRE_POSTGRES=1</code>). Features like pgvector embeddings, <code>pg_trgm</code> search, and native JSON operators need Postgres. Alembic migrations are forward-only and tested against both backends where dual SQL exists."},
            {"q": "When does SQLite still appear?", "a": "SQLite is the zero-config test/dev fallback when <code>DATABASE_URL</code> is empty and Postgres is not required. CI default pytest uses SQLite; operators must run Postgres-backed tests before merging <code>db/</code> changes. Health reports <code>backend: sqlite</code> vs <code>postgresql</code>."},
            {"q": "How does the asyncpg pool work?", "a": "<code>DATABASE_POOL_SIZE</code> configures concurrent connections. Drawer bundle assembly intentionally uses separate connections per sub-fetch for safe parallelism. <code>DATABASE_POOL_COMMAND_TIMEOUT_SECONDS</code> caps SQL wait time separately from per-feed HTTP timeouts."},
            {"q": "What is <code>db/pg_adapt.py</code>?", "a": "It adapts Postgres-native SQL for SQLite compatibility in the test suite\u2014parallel <code>_SQLITE</code> / <code>_PG</code> query constants where needed. Production path is Postgres-only; do not reintroduce a generic dialect translation layer."},
            {"q": "How are migrations managed?", "a": "Alembic revisions in <code>backend/alembic/versions/</code> are forward-only. Never edit applied migrations; add a new revision. Reserved words like <code>references</code> caused real bugs\u2014prefer renamed columns over quoted identifiers."},
            {"q": "What tables anchor CVE data?", "a": "<code>cves</code> holds core NVD fields; satellite tables cover KEV deadlines, EPSS history, OTX mirrors, embeddings, Sigma rules index, and correlation artifacts. Ingest jobs upsert idempotently with watermarks in <code>sync_state</code>."},
            {"q": "Explain <code>sync_state</code> usage.", "a": "Key-value store for job watermarks: NVD cursor, EPSS file SHA256, SigmaHQ commit hash, rate-limit buckets when using DB store, and feature checkpoints. Lets incremental syncs skip unchanged work\u2014e.g., EPSS identity skip when CSV hash unchanged."},
            {"q": "What is <code>feed_cache</code>?", "a": "TTL JSON blobs for expensive or slow paths: OTX pulses, detection context, LLM outputs, and more. Distinct from canonical tables\u2014read paths may serve stale mirror rows on upstream 4xx/5xx without deleting cached intel."},
            {"q": "How does transaction boundary discipline work?", "a": "<code>db/txn_boundaries.py</code> ensures NVD ingest commits before CIRCL/Sploitus enrich so slow sources cannot exhaust the writer pool. Long-running jobs batch commits; request handlers keep transactions short."},
            {"q": "What indexing supports feed performance?", "a": "KEV JOIN optimizations, count caches, <code>pg_trgm</code> for search, and keyset pagination on <code>/api/cves</code> (<code>pagination=keyset</code>). ORJSON accelerates default JSON responses."},
            {"q": "How are user preferences persisted?", "a": "<code>user_preferences</code> stores display settings, timezone, and optional asset profile JSON. Stack terms use <code>GET/PUT /api/me/stack</code> with legacy localStorage migration on login."},
            {"q": "What is <code>app_settings</code>?", "a": "Writable operator config survives deploys when env vars are unset. Precedence: process env \u2192 DB \u2192 <code>.env</code>. Secret fields encrypt with <code>BRIEFR_SETTINGS_KEY</code>. Admin Save can mirror to <code>.env</code> for compatibility."},
            {"q": "How does the database shim relate to ARCH?", "a": "PM-3 security architecture graph uses <code>database</code> shim helpers for one-hop SQL edges in the corpus view. Runtime product data still flows through the main <code>db/</code> package\u2014not the shim\u2014for CVE operations."},
            {"q": "What integrity checks exist?", "a": "SQLite: <code>PRAGMA integrity_check</code>. Postgres: real <code>pg_catalog</code> probes for invalid indexes, unvalidated constraints, and FK orphans. Admin Overview runs Check DB integrity with method + backend reported."},
            {"q": "How are embeddings stored?", "a": "pgvector extension on Postgres 16 (<code>pgvector/pgvector:pg16</code> image). Entity embeddings for CVEs, techniques, and campaigns with <code>content_hash</code> drift re-embed on backfill. SQLite tests skip vector-specific paths."},
            {"q": "What is the Procrastinate schema?", "a": "Alembic revision <code>028</code> applies Procrastinate tables when enabled. Jobs like <code>jobs:llm_product_extraction</code> use queueing locks for singleton execution across workers."},
            {"q": "How would you debug a slow query?", "a": "Check <code>DATABASE_POOL_COMMAND_TIMEOUT_SECONDS</code>, inspect structured logs with <code>request_id</code>, use admin DB explorer with filtered <code>cve_id</code>, and run pytest both SQLite and Postgres for regression. EXPLAIN on production is operator-driven outside the app."},
            {"q": "Why no ORM?", "a": "Explicit SQL in the <code>db/</code> package keeps query shapes visible for performance tuning and dual-backend tests. FastAPI Pydantic models validate API boundaries; SQL stays close to Postgres features."},
            {"q": "What happens on first boot with an empty database?", "a": "If fewer than 10 CVE rows exist, startup triggers full NVD\u2192KEV\u2192EPSS ingest (network-heavy). Operators can seed via <code>scripts/seed_screenshot_data.py</code> for instant demo data."},
        ],
    },
    {
        "slug": "iv-ingest-scheduler",
        "page_id": "iv-ingest-scheduler",
        "chapter_num": "Interview \u00b7 4",
        "title": "Ingest & scheduler",
        "dek": "APScheduler jobs, locks, api_queue, watermarks, and operator refresh honesty.",
        "prev": ("iv-backend-db.html", "Backend & database"),
        "next": ("iv-correlation-scoring.html", "Correlation & scoring"),
        "questions": [
            {"q": "What schedules recurring work?", "a": "APScheduler inside <code>scheduler.py</code>, started from FastAPI lifespan when <code>BRIEFR_SCHEDULER_ENABLED=1</code>. ~27 normal jobs plus optional registration-gated jobs (OTX continuous, exploit sources, detection LLM, SigmaHQ sync)."},
            {"q": "How are duplicate job runs prevented?", "a": "Each job uses <code>max_instances=1</code>, <code>coalesce=True</code>, and a per-job <code>asyncio.Lock</code> in <code>scheduler_locks._LOCKS</code>. Manual admin Run Now shares the same lock mapping via <code>_JOB_RUN_MAP</code> in <code>routers/admin/jobs.py</code>."},
            {"q": "Name core ingest jobs.", "a": "<code>nvd_incremental_sync</code>, <code>kev_metadata_sync</code>, <code>epss_score_sync</code>, <code>weekly_mitre_refresh</code>, <code>vulnrichment_snapshot_sync</code>, <code>cvelistv5_incremental_sync</code>\u2014each writes canonical tables with watermarks."},
            {"q": "What does NVD incremental sync do?", "a": "Pulls modified CVEs from NVD API through the resilient client with circuit breaker and <code>api_queue</code> pacing. Commits core rows before optional enrichments. Respects API key headers when <code>NVD_API_KEY</code> is set."},
            {"q": "How does EPSS identity skip work?", "a": "Downloads the FIRST CSV.GZ, compares SHA256 and <code>score_date</code> to <code>sync_state</code>. Unchanged file skips gunzip, parse, and upsert\u2014saving CPU on daily runs. Force via admin EPSS force-resync."},
            {"q": "What is feed health vs circuit health?", "a": "Feed health tracks sync freshness and last success per source. Circuit breaker state tracks consecutive failures for outbound HTTP. API key health probes are separate\u2014they do not open/clear shared circuits used by real traffic."},
            {"q": "Explain the API queue serialization.", "a": "Outbound requests for rate-limited APIs enter a per-source queue. Health endpoint exposes task-level status. Background sync UI groups by provider and distinguishes waiting vs queued tasks."},
            {"q": "What is catch-up mode?", "a": "Admin-only time-boxed backlog drain: raises embeddings/correlation caps and LLM pacing headroom. <code>catchup_tick</code> every 5 minutes nudges eligible work. Still respects <code>api_queue</code>, Retry-After, and rate-limit floors."},
            {"q": "How does stack backfill work?", "a": "<code>STACK_BACKFILL_ENABLED</code> opt-in historical NVD+KEV+EPSS for shallow stack coverage. Checkpointed per product with atomic <code>claim_run_running</code> gate. Procrastinate can defer resume after NVD rate limits."},
            {"q": "What retention jobs run?", "a": "<code>cache_retention_cleanup</code> sweeps stale <code>ioc_cache</code>/<code>feed_cache</code>, ages <code>epss_history</code>, OTX mirrors, <code>ai_operations</code> (30d), webhook logs, and crash-stranded webhook dedupe claims."},
            {"q": "How are watchlist alerts emitted?", "a": "<code>watchlist_monitor_alerts</code> scheduler job detects KEV entry or EPSS/PoC changes on pinned CVEs and fires <code>watchlist_alert</code> webhooks. Snooze was removed from UI; pin/watchlist remains."},
            {"q": "What is <code>sigmahq_index_sync</code>?", "a": "Weekly default job mirrors SigmaHQ tarball into Postgres with commit+sha256 watermark. Admin can force re-sync clearing watermark. Detect tab prefers this local index over live GitHub search."},
            {"q": "How does OTX ingest behave on errors?", "a": "OTX pulses cache in <code>feed_cache</code> and mirror tables. Upstream 4xx/5xx serves any-age stale rows without deleting cached pulses\u2014honest degradation for analysts."},
            {"q": "What startup one-shots exist?", "a": "Full ingest when CVE count &lt; 10; deferred summary, EPSS history, exploit-source, and MITRE/ATLAS maintenance when data is sparse. These are not recurring cron entries but lifespan-triggered bootstrap."},
            {"q": "How do manual refresh routes interact with locks?", "a": "Admin Feed Health Sync and Scheduler Run Now call the same async locks as cron jobs so operators cannot double-run NVD or correlation jobs concurrently."},
            {"q": "What is honest about FEED footer refresh timing?", "a": "Footer next refresh reflects <code>nvd_incremental_sync</code> only. Orphaned <code>CACHE_REFRESH_*</code> env vars are not scheduled\u2014health <code>refresh_schedule</code> is null. No misleading auto-daily copy."},
            {"q": "How does metering relate to ingest?", "a": "<code>API_CALL_EVENTS_ENABLED</code> records every <code>resilient_request</code> attempt to <code>api_call_events</code> with source, latency, and actor/job IDs. Admin API keys page shows 24h breakdowns."},
            {"q": "What jobs are registration-gated?", "a": "<code>otx_continuous_sync</code>, <code>exploit_sources_sync</code>, <code>detection_context_llm</code>, <code>sigmahq_index_sync</code> register only when their feature flags enable them. <code>detection_context_llm</code> needs restart to register."},
            {"q": "How would you recover a stuck scheduler job?", "a": "Check Application logs with <code>job_id</code> + <code>run_id</code> from Scheduler table link, verify lock holder, inspect feed health circuit state, and use admin Run after upstream recovery. For stack backfill, stale <code>running</code> reclaims after <code>STACK_BACKFILL_STALE_SECONDS</code>."},
        ],
    },
    {
        "slug": "iv-correlation-scoring",
        "page_id": "iv-correlation-scoring",
        "chapter_num": "Interview \u00b7 5",
        "title": "Correlation & scoring",
        "dek": "Operational Priority, Threat Score, environment relevance, and explainable correlation.",
        "prev": ("iv-ingest-scheduler.html", "Ingest & scheduler"),
        "next": ("iv-ml-embeddings.html", "ML & embeddings"),
        "questions": [
            {"q": "What is Operational Priority (OP)?", "a": "OP is the primary analyst-facing band (P1\u2013P4) for triage. It combines KEV status, severity, EPSS exploitation signals, environment relevance to the user's stack, and optional profile toggles (<code>internet_facing</code>, <code>criticality</code>). OP can escalate one band under documented rules without changing Threat Score."},
            {"q": "What is Threat Score?", "a": "A 0\u2013100 asset-independent score from the backend <code>scoring/</code> engine. CISA KEV sets a floor of 80 when <code>is_kev</code>. VulnCheck-only KEV has no floor. The frontend displays <code>POST /api/cves/{id}/risk</code> fields only\u2014no live Threat recompute in the browser."},
            {"q": "How does Environment Relevance work?", "a": "Tier reflects stack term matching against affected products/CPEs. UNKNOWN is provisional\u2014no phantom points. Server-side stack relevance sort (I16) can order the feed when configured. My Stack persists via <code>/api/me/stack</code>."},
            {"q": "What is SSVC's role?", "a": "Parallel annotation on <code>/risk</code>: outcomes Act, Attend, Track*, Track with explainability <code>path</code>. SSVC does not replace OP; crosswalk P1\u2194Act, P2\u2194Attend, etc. Profile fields may modify SSVC without touching Threat."},
            {"q": "Describe correlation v3 at a glance.", "a": "Nightly and on-demand correlation clusters OTX pulses into campaigns, infrastructure lanes, actor/sector signals, and temporal patterns\u2014persisted in Postgres, served over REST. OP hero renders from cheap signals immediately; campaign escalation merges when correlation loads client-side."},
            {"q": "Why is correlation explainable?", "a": "Lanes surface structured factors and matching rationale\u2014not a black-box model score. Campaign clustering uses normalized pulse titles; Active Campaigns UI shows primary card plus related count with honest empty states."},
            {"q": "What is <code>CORRELATION_PRECOMPUTE_ENABLED</code>?", "a": "Optional snapshot precompute behind a flag (default off). When off, <code>POST /api/cves/{id}/risk</code> no longer blocks on correlation\u2014improving drawer open latency. Escalation merges when correlation data arrives."},
            {"q": "How does OP escalation interact with correlation?", "a": "Client-side merge may raise OP one band when correlation shows HIGH/MED campaign linkage\u2014temporary documented behavior in SYSTEM_DESIGN. Threat formula stays unchanged; low EPSS never de-escalates KEV/CRIT P1."},
            {"q": "What inputs feed the scoring engine?", "a": "KEV flags, CVSS, EPSS score and percentile, CWE, affected products, Vulnrichment SSVC, stack terms, and optional user profile JSON. Legacy v1.1b blend remains as <code>legacy_risk_v11b</code> API field only."},
            {"q": "Where is scoring code?", "a": "<code>backend/scoring/</code> is the sole engine\u2014<code>priority.py</code>, threat modules, and SSVC helpers. DetailDrawer and wallboard consume API output; duplicated FE scoring was explicitly removed (W2)."},
            {"q": "How does KEV affect prioritization?", "a": "KEV is a strong P1 signal with Threat floor 80 for CISA KEV. KEV due-date histograms and backlog views in Forge use unified UTC math. KEV-on-stack webhooks use <code>BRIEFR_STACK_TERMS</code> or saved user stack."},
            {"q": "What is the Investigation Score route status?", "a": "Removed. Overview uses OP + Threat + Environment Relevance per ADR-002. Interview answer: do not describe Investigation Score as current\u2014it is historical."},
            {"q": "How does feed ranking use scores?", "a": "Server-side stack relevance sort option; wallboard top-risk orders by OP then Threat. Feed cards show KEV ransomware badge and EPSS context without recomputing Threat client-side."},
            {"q": "What is <code>nightly_correlation</code> job?", "a": "Scheduled correlation pass over OTX and related intel tables\u2014no live external API inside the engine run. Results feed Intel tab campaigns and Forge overlays when enabled."},
            {"q": "How are campaigns displayed in the drawer?", "a": "Active Campaigns clusters related pulses by normalized base title; default collapsed section; humanized titles via <code>formatIntelLabel</code>. Matching uses stronger <code>normalize_pulse_name</code> than display formatting."},
            {"q": "What is environment UNKNOWN honesty?", "a": "UNKNOWN tier means insufficient stack evidence\u2014scoring does not invent relevance points. Asset wizard optional toggles affect OP/SSVC only when set."},
            {"q": "How does semantic search relate to scoring?", "a": "Hybrid search (<code>/api/search/semantic</code>) retrieves CVEs, techniques, and campaigns via embeddings\u2014retrieval only, not a replacement for OP/Threat. Results render in sectioned FEED UI."},
            {"q": "What regression tests guard scoring?", "a": "Backend pytest covers priority bands, KEV floors, SSVC paths, and API <code>/risk</code> contracts. Frontend unit tests cover display helpers. Golden query contracts exist for embeddings\u2014not for OP math duplication in FE."},
            {"q": "How would you explain scoring to a non-security hiring manager?", "a": "BRIEFR translates CVE noise into three numbers analysts already use: how urgent (P1\u2013P4), how dangerous in general (Threat 0\u2013100), and whether it hits our stack (Environment). All computed server-side so every UI surface agrees."},
        ],
    },
    {
        "slug": "iv-ml-embeddings",
        "page_id": "iv-ml-embeddings",
        "chapter_num": "Interview \u00b7 6",
        "title": "ML & embeddings",
        "dek": "pgvector retrieval, LLM router, pacing, and what ML does not own in BRIEFR.",
        "prev": ("iv-correlation-scoring.html", "Correlation & scoring"),
        "next": ("iv-detection-forge.html", "Detection & Forge"),
        "questions": [
            {"q": "Are embeddings required?", "a": "No. <code>EMBEDDINGS_ENABLED=1</code> gates nightly <code>embeddings_backfill</code> and semantic search. Requires pgvector on Postgres 16. Retrieval only\u2014no RAG chat over CVE corpus in the core product."},
            {"q": "What entities get embedded?", "a": "CVEs, ATT&amp;CK techniques, and non-retracted <code>correlation_campaigns</code> (E8). <code>content_hash</code> drift triggers re-embed on scheduled backfill. Caps: ingest max 25, backfill max 2000 per run."},
            {"q": "What is <code>EMBEDDINGS_AUTO_ON_INGEST</code>?", "a": "Defaults on when embeddings enabled\u2014new/changed CVEs enqueue embed work on ingest. Admin can disable auto-on-ingest independently. CPU-only local embedding model\u2014no GPU requirement documented."},
            {"q": "How does hybrid semantic search work?", "a": "<code>/api/search/semantic</code> combines vector similarity with stack/severity/KEV filters. FEED renders Techniques / Campaigns / CVEs sections. My Stack context stays on during hybrid mode."},
            {"q": "Describe the LLM provider router.", "a": "Scheduler-side chain: Groq \u2192 Cerebras \u2192 OpenRouter free tier \u2192 Gemini, centralized in <code>ai/model_catalog.py</code>. PDF summaries and product extraction use the router. Anthropic was removed from the chain."},
            {"q": "What is LLM pacing (K5)?", "a": "<code>ai/llm_pacing.py</code> holds ~85% headroom below provider RPM/TPM ceilings. Prevents burning quotas during batch jobs. Catch-up mode raises headroom temporarily."},
            {"q": "What gets logged in <code>ai_operations</code>?", "a": "Redacted metadata per <code>chat_completion_task</code> attempt\u2014no prompt text by default. Token counts when providers return usage. Admin AI Operations page: Overview, Providers, Models, Usage, Activity tabs."},
            {"q": "How do empty LLM responses degrade?", "a": "Blank bodies count toward circuit health. Scheduler jobs use <code>llm_job_session()</code> to skip a failing provider for remaining CVEs in that run while still failing over on first empty response."},
            {"q": "What is detection context LLM (K4)?", "a": "<code>detection_context_llm</code> job extracts paths, params, keywords from CVE/exploit text into <code>feed_cache</code> keys <code>detection_ctx:{cve_id}</code>. Disabled by default (<code>DETECTION_CONTEXT_LLM_ENABLED=0</code>); restart required to register job."},
            {"q": "How does Nuclei parsing relate to ML?", "a": "Deterministic Nuclei YAML parser (D4) enriches detection context artifacts on exploit sync\u2014default on. LLM extract is an optional overlay, not the primary path."},
            {"q": "What quotas does AI-3 expose?", "a": "Advisory snapshots from provider rate-limit response headers in <code>ai/quota.py</code>. Surfaced on AI Operations provider rows and overview <code>quota_warnings</code>\u2014informational, not hard enforcement."},
            {"q": "Can admins replay failed LLM operations?", "a": "Yes\u2014Program E: view payload and <code>POST .../retry</code> with replay provenance, circuit-open guard unless <code>force=true</code>, and audit entries. Activity rows show <code>has_payload</code> when captured."},
            {"q": "Why skip LLM calls on empty text?", "a": "Cost and quota protection\u2014<code>llm_payload.py</code> enforces at router and client layers. Prevents noop provider HTTP when CVE description or exploit text is blank."},
            {"q": "What models are defaults in 2026?", "a": "OpenRouter free Gemini Flash-Lite IDs went stale; catalog SSOT updated to working IDs. Operators should clear old <code>OPENROUTER_MODEL_*</code> env overrides so defaults apply."},
            {"q": "Is vision used?", "a": "Deferred until image inputs exist in the pipeline. Router supports text tasks today; Cerebras gemma vision noted for future detection artifact extraction."},
            {"q": "How does retrieval health reporting work?", "a": "<code>GET /api/admin/retrieval/health</code> shows embedding counts by entity, pending work, extension presence, last backfill. Coupled to AI ops panel\u2014not a separate silo."},
            {"q": "What is NOT done with LLMs?", "a": "Threat/OP scores are rule-based, not LLM-generated. Generic detection dumps are suppressed. No unauthenticated summarization endpoints. LLMs assist optional enrichment and operator-facing PDF summaries."},
            {"q": "How do embeddings interact with catch-up?", "a": "Catch-up tick includes embeddings backfill when enabled, along with correlation precompute and CPE catalog sync\u2014subject to existing gates and locks."},
            {"q": "How would you answer 'why local embeddings vs API-only'?", "a": "Local CPU embeddings keep recurring cost predictable for self-hosters and avoid shipping CVE text to a third party for every search. Optional cloud LLMs remain for tasks that need generative output, with explicit operator keys."},
        ],
    },
    {
        "slug": "iv-detection-forge",
        "page_id": "iv-detection-forge",
        "chapter_num": "Interview \u00b7 7",
        "title": "Detection & Forge",
        "dek": "SigmaHQ index, class router, DetectionContext, and Forge navigator workflows.",
        "prev": ("iv-ml-embeddings.html", "ML & embeddings"),
        "next": ("iv-frontend-ux.html", "Frontend & UX"),
        "questions": [
            {"q": "What is the Detect tab's purpose?", "a": "Surface detection content for a CVE: community Sigma rules from the local SigmaHQ index, BRIEFR class templates when appropriate, SIEM queries, and log patterns\u2014driven by a unified class router so all three agree on class."},
            {"q": "How does SigmaHQ indexing work?", "a": "<code>sigmahq_index_sync</code> mirrors the SigmaHQ tarball into Postgres with commit and SHA256 watermark. <code>find_sigma_rules</code> prefers CVE-exact local matches with DRL attribution. Live GitHub search is fallback only when index empty."},
            {"q": "What is <code>match_basis</code> honesty?", "a": "UI distinguishes never-synced index, empty index, no CVE-exact match, and community vs BRIEFR template sources. BRIEFR YAML is suppressed when community hits exist or template would be <code>generic</code>."},
            {"q": "Explain BRIEFR class templates.", "a": "Deterministic templates keyed by ATT&amp;CK technique when mapped, else CWE (<code>briefr_basis</code>), never generic dumps. <code>class_router.py</code> resolves class consistently for Sigma, SIEM, and log patterns."},
            {"q": "What is <code>DetectionContext</code>?", "a": "Scaffold in <code>feed_cache</code> as <code>detection_ctx:{cve_id}</code> with CWE, product, class, artifacts, model metadata. Written by <code>detection_context_sync</code> job (default off) and Nuclei/LLM enrichers when enabled."},
            {"q": "What does Forge provide?", "a": "ATT&amp;CK navigator matrix, hunt packs, threat scenarios, proof bench, KEV backlog, and coverage views. Top tabs switch views; matrix click toggles technique selection. Hunt pack generation shares detection engine with Detect tab\u2014no LLM required."},
            {"q": "How does Forge link to the drawer?", "a": "Drawer MITRE section pivots to Forge navigator; hunt-pack CVE chips open the drawer. URL sync uses <code>?tab=forge</code> plus <code>view</code>/<code>technique</code> params with history push for back button."},
            {"q": "What is detection composer status?", "a": "DC-1\u2026DC-4 shipped for evidence pack and emit Sigma/SIEM/YARA via shared engine. Broader composer UX may expand, but core emit paths are live in Detect and Forge generate."},
            {"q": "How does KEV backlog appear?", "a": "Scheduler <code>kev_backlog_reconcile</code> and <code>detection/backlog.py</code> emit <code>kev_backlog</code> notifications deep-linking to Forge <code>?view=backlog</code>. Surfaces gaps between KEV and detection coverage."},
            {"q": "What is community-Sigma-first policy?", "a": "Detect prefers community SigmaHQ rules over generated BRIEFR templates when CVE-exact matches exist. Reduces noise and respects SigmaHQ authorship with Show YAML and attribution strings."},
            {"q": "How do artifacts merge from Nuclei?", "a": "<code>DETECTION_CONTEXT_NUCLEI_ENABLED=1</code> default parses Nuclei YAML on exploit sync into detection context; merges keywords/paths into emitted BRIEFR templates when present."},
            {"q": "What SIEM outputs exist?", "a": "Class-aware queries selected by <code>class_router</code>\u2014same class as Sigma and log patterns. Export paths live in detection module consumed by Detect UI and Forge hunt-pack generate."},
            {"q": "How is Forge coverage honest?", "a": "Empty/sparse matrix uses shared <code>EmptyState</code>\u2014no forced tall black columns. Campaign clusters avoid 'ranked for your stack' without stack pins. Wallboard distinguishes global vs stack-scoped empty copy."},
            {"q": "What ATT&amp;CK navigator UX shipped (PM-4d)?", "a": "Top view tabs; tactic columns with id + name; click toggles selection; hunt pack only on coverage view. Removed GAP/COMMUNITY/YOURS chrome for clarity."},
            {"q": "Can Forge generate without cloud AI?", "a": "Yes\u2014hunt pack generate and detection emit paths are deterministic from structured CVE context and Sigma index. LLM is optional overlay for richer artifacts, not a gate."},
            {"q": "How are detection flags configured?", "a": "Admin config exposes <code>DETECTION_CONTEXT_*</code> and <code>SIGMAHQ_INDEX_SYNC_*</code> with honest apply strategies\u2014immediate vs restart for LLM job registration."},
            {"q": "What tests cover detection?", "a": "<code>test_sigmahq_index.py</code>, <code>test_sigmahq_index_read.py</code>, class router tests, and admin job map tests ensure scheduler wiring matches <code>run_sigmahq_index_sync</code>."},
            {"q": "How does Detect relate to IOC tab?", "a": "IOC tab is live enrichment lookup (VT, AbuseIPDB, GreyNoise)\u2014separate from rule generation. Detection uses persisted CVE context and Sigma index, not IOC query results directly."},
            {"q": "How would you demo Detect in an interview?", "a": "Open a KEV CVE with Sigma index synced\u2014show community rules with attribution, contrast with CWE-based BRIEFR template on unmapped technique, and pivot to Forge matrix for coverage context."},
        ],
    },
    {
        "slug": "iv-frontend-ux",
        "page_id": "iv-frontend-ux",
        "chapter_num": "Interview \u00b7 8",
        "title": "Frontend & UX",
        "dek": "React 19, Radix, semantic tokens, DetailDrawer patterns, and accessibility.",
        "prev": ("iv-detection-forge.html", "Detection & Forge"),
        "next": ("iv-api-ops.html", "API & operations"),
        "questions": [
            {"q": "Why no Tailwind?", "a": "ADR-003 mandates plain CSS with semantic tokens in <code>tokens.css</code>\u2014dark terminal identity, no Tailwind runtime. shadcn patterns are reference-only, re-skinned to BRIEFR CSS. Mantine/MUI/Chakra are prohibited per ADR-005."},
            {"q": "What UI primitives are standard?", "a": "Radix: Checkbox, Switch, Dialog, Select, Tabs, DropdownMenu, Tooltip, Popover, ScrollArea\u2014styled with design tokens. Zero native <code>&lt;select&gt;</code> or checkbox inputs in new code (grep gates in verify-local)."},
            {"q": "How are colors managed?", "a": "Semantic tokens only: <code>--surface-*</code>, <code>--text-*</code>, <code>--severity-*</code>, <code>--accent-selected</code> for active states. Red is destructive/critical only\u2014not for links or selection. Brand orange <code>#e85533</code> via <code>--accent-primary</code>."},
            {"q": "What is the async region pattern?", "a": "Every async view implements loading skeleton, empty, error with request-id, and data states. Empty and error must look distinct. Long LOCKED jobs show progress message plus indeterminate bar."},
            {"q": "How does the command palette work?", "a": "\u2318K command palette (Track E) for wayfinding\u2014portaled, keyboard accessible. Global shortcuts ignore modifiers when text is selected; drawer and tab state preserved."},
            {"q": "What chart library is used?", "a": "Recharts behind <code>ChartShell</code> with fixed-height wrappers and <code>maintainAspectRatio: false</code>. EPSS sparklines remain custom SVG. Chart.js was fully removed."},
            {"q": "How does DateTimePicker work?", "a": "Shared <code>DateTimePicker</code> / <code>DateTimeRangeField</code> with DD-MM-YY HH:mm:ss and dropdown selects\u2014never native <code>datetime-local</code> in new code per design system \u00a723."},
            {"q": "What is FEED performance work?", "a": "Scroll isolation, <code>content-visibility: auto</code> windowing (I15), keyset pagination, parallel drawer bundle fetches. Filters and scroll survive tab hidden panels."},
            {"q": "How is auth wired in the frontend?", "a": "<code>AuthContext</code> bootstraps via <code>fetchMe()</code> only\u2014never bare refresh on load. <code>RequireAuth</code> wraps analyst routes matching backend session gate (#441)."},
            {"q": "What motion rules apply?", "a": "120\u2013180ms transitions on transform/opacity only; respect <code>prefers-reduced-motion</code> and global <code>data-motion</code> toggle on <code>&lt;html&gt;</code>. No layout property animation."},
            {"q": "How does admin differ visually?", "a": "Shared tokens but denser tables via <code>AdminDataGrid</code>, uppercase mono wayfinding breadcrumbs, collapsible config sections, sticky apply bar. Typography enforces 12px minimum via <code>--type-*</code> scale."},
            {"q": "What is the DataGrid pattern?", "a": "Shared <code>DataGrid</code> with <code>table-layout: fixed</code> and shared <code>&lt;col&gt;</code> definitions so column resize keeps header/body aligned."},
            {"q": "How are toasts handled?", "a": "Shared toast tray: errors persist until dismissed; success auto-dismiss 8s; max 4 visible; pause on hover. Backend restart uses top banner via health poll\u2014not a fleeting toast."},
            {"q": "What accessibility baseline?", "a": "WCAG 2.1 AA: focus rings via <code>--focus-ring</code>, icon-only controls need <code>aria-label</code>, interactive targets \u226524px. Tooltips explain status pills\u2014design principle 1."},
            {"q": "How does URL state work for Forge?", "a": "<code>?tab=forge</code> with <code>view</code>, <code>technique</code>, <code>pack</code> params. Intentional navigations push history; cosmetic param hygiene uses replaceState."},
            {"q": "What is dark-mode-only policy?", "a": "Light theme removed (W6)\u2014do not reintroduce without ADR. <code>tokens.css</code> assumes dark surfaces; contrast uses <code>--text-muted</code> floor."},
            {"q": "How is stack input persisted?", "a": "<code>GET/PUT /api/me/stack</code> with legacy <code>briefr_stack</code> localStorage migration on login. Feed filter bar and asset wizard consume server stack."},
            {"q": "What lint gates protect UI quality?", "a": "<code>verify-local.sh</code> runs design-token lint, native control grep gates, frontend build, and scoped ESLint on scoring + admin pages."},
            {"q": "How would you add a new analyst page?", "a": "Follow Primitives \u2192 Composites \u2192 Features layering, reuse Radix + tokens, implement four async states, wire URL tab sync if needed, and update design-system.md if introducing a new pattern."},
        ],
    },
    {
        "slug": "iv-api-ops",
        "page_id": "iv-api-ops",
        "chapter_num": "Interview \u00b7 9",
        "title": "API & operations",
        "dek": "Health, admin diagnostics, webhooks, notifications, and structured logging.",
        "prev": ("iv-frontend-ux.html", "Frontend & UX"),
        "next": ("iv-devops-deploy.html", "DevOps & deploy"),
        "questions": [
            {"q": "How is the API organized?", "a": "FastAPI routers under <code>routers/</code>: analyst CVE/feed/search, auth, me/preferences, IOC, Forge, wallboard, admin packages. ORJSON default response class for speed. Global exception handler returns generic 500 with <code>request_id</code>."},
            {"q": "What auth middleware applies?", "a": "Session middleware validates <code>briefr_at</code> cookie on analyst <code>/api/*</code>. Admin routes check <code>admin</code> role. Wallboard routes accept header token. LLM summary endpoints require logged-in user."},
            {"q": "What does <code>/api/health</code> expose?", "a": "Backend kind (postgres/sqlite), scheduler enabled flag, refresh schedule honesty, outbound queue per source, and dependency readiness. Frontend polls for restart banner and onboarding checklist."},
            {"q": "How are errors returned?", "a": "Expected 4xx: <code>HTTPException</code> with short safe <code>detail</code>. Unexpected: generic 500 JSON with <code>request_id</code>; full traceback only in structured logs. Frontend shows detail plus X-Request-ID ref line."},
            {"q": "What is the drawer bundle endpoint?", "a": "<code>GET /api/cves/{id}/drawer</code> orchestrates parallel sub-fetches\u2014each uses its own DB connection. Reduces round trips for DetailDrawer tabs while staying asyncpg-safe."},
            {"q": "How does keyset pagination work?", "a": "<code>GET /api/cves</code> supports <code>pagination=keyset</code> for stable large-feed traversal alongside legacy offset if present. Pair with server-side stack relevance sort for personalized feeds."},
            {"q": "What admin diagnostics exist?", "a": "Support pack export, corpus drift check, DB integrity probe, retrieval health, API usage metering, and application log ring buffer filtered by job/run id."},
            {"q": "How do webhooks work?", "a": "Database-backed destinations with per-destination event subscriptions, dedupe keys, delivery log, and health cards. Scheduler emits watchlist, KEV backlog, and operator events. Test POST works on disabled destinations."},
            {"q": "What is the notification center?", "a": "<code>user_notifications</code> backs analyst bell (watchlist, KEV backlog) and admin StatusBar bell (job errors, unhealthy keys, webhook failures). Open marks seen; dismiss with undo."},
            {"q": "How is config applied?", "a": "<code>GET /api/admin/config/schema</code> exposes <code>apply_strategy</code>: immediate, scheduler_reschedule, or restart. Interval saves reschedule APScheduler triggers without full process restart when possible."},
            {"q": "What metering endpoints exist?", "a": "<code>GET /api/admin/api-usage/metering</code> for 24h by-source and by-actor breakdown from <code>api_call_events</code>. Complements API key health probes."},
            {"q": "How does stack catalog suggest work?", "a": "<code>GET /api/stack/catalog/suggest</code> (\u22653 chars) typeahead from <code>software_catalog</code> when CPE catalog sync enabled\u2014merged with curated lists in asset wizard."},
            {"q": "What rate limits apply to admin?", "a": "Token buckets on destructive or expensive routes\u2014e.g., DB explorer 30/min. Refresh and auth endpoints have dedicated limits to prevent brute force and token stuffing."},
            {"q": "How is wallboard API secured?", "a": "<code>X-BRIEFR-Wallboard-Token</code> header required; optional config token. No query-string token. Ranked tiles use OP then Threat fields."},
            {"q": "What structured logging fields help ops?", "a": "JSON logs: <code>ts</code>, <code>level</code>, <code>request_id</code>, <code>briefr.access</code> lines with duration_ms. Job context adds <code>job_id</code> and <code>run_id</code> in scheduler runs."},
            {"q": "Are there public unauthenticated APIs?", "a": "Health may be open for load balancers; analyst intel routes are not. Setup route only before first user exists. Self-hosted assumes trusted network or edge auth for defense in depth."},
            {"q": "How does semantic search API behave?", "a": "<code>/api/search/semantic</code> accepts query plus filters; returns typed sections for techniques, campaigns, CVEs when embeddings enabled. Empty embeddings gracefully degrade."},
            {"q": "What is intel snapshot export?", "a": "<code>scripts/export_intel_snapshot.py</code> allowlisted tables per DATA_SNAPSHOT.md with manifest version 1. Import/verify scripts support migration between instances\u2014operator tooling, not daily API."},
            {"q": "How would you version breaking API changes?", "a": "BRIEFR favors additive JSON fields and feature flags. Breaking changes require PRODUCT_STATUS, API_REFERENCE, and frontend contract tests updates in the same PR\u2014deploy scripts promise additive compatibility."},
        ],
    },
    {
        "slug": "iv-devops-deploy",
        "page_id": "iv-devops-deploy",
        "chapter_num": "Interview \u00b7 10",
        "title": "DevOps & deploy",
        "dek": "Production layout, verify-local, backups, migrations, and multi-worker ops.",
        "prev": ("iv-api-ops.html", "API & operations"),
        "next": ("iv-product-behavioral.html", "Product, behavioral & solo owner"),
        "questions": [
            {"q": "What does production deployment look like?", "a": "Code at <code>/opt/briefr</code>, Postgres 16 often Docker at <code>/opt/infra/postgres</code>, nginx serving <code>frontend/dist</code>, systemd <code>briefr-backend.service</code> running uvicorn on :8000, age-encrypted backups under <code>/var/lib/briefr/backups</code>."},
            {"q": "Is full docker-compose shipped?", "a": "Postgres compose exists (<code>deploy/docker-compose.postgres.yml</code> with pgvector image). All-in-one platform compose is planned\u2014not the current production reference path."},
            {"q": "What is <code>verify-local.sh</code>?", "a": "Pre-merge gate mirroring CI: SQLite pytest, dependency audit, frontend build, unit tests, scoped lint. <code>--full</code> adds Postgres pytest, gitleaks, Playwright smoke. Green local verify suffices when GitHub Actions quota is exhausted."},
            {"q": "How are backups handled?", "a": "Scheduled backup job plus deadman check. Postgres CI runs backup round-trip test. Admin UI exposes backup status; Download DB removed for Postgres\u2014legacy SQLite export route remains dev-only."},
            {"q": "What does <code>briefr-doctor.sh</code> do?", "a": "Deploy script runs health/import checks and optional support pack download\u2014operator diagnostics on the live box without manual curl juggling."},
            {"q": "How do migrations run in deploy?", "a": "Alembic upgrade on deploy before uvicorn restart. Forward-only\u2014roll forward fixes, never edit stamped revisions. Postgres apply required before merge for DDL changes."},
            {"q": "What CI jobs exist?", "a": "test, dependency-audit, frontend build, frontend unit tests; full adds Postgres tests, gitleaks (known red), Playwright smoke. dependency-audit and gitleaks are known non-blockers per CLAUDE.md."},
            {"q": "How is nginx configured?", "a": "Serves static frontend, proxies <code>/api</code> to uvicorn on localhost. TLS typically terminates at nginx or Cloudflare tunnel\u2014not inside FastAPI."},
            {"q": "What env vars matter for ops?", "a": "<code>DATABASE_URL</code>, <code>JWT_SECRET</code>, <code>BRIEFR_REQUIRE_POSTGRES=1</code>, <code>RATE_LIMIT_ENABLED=1</code>, <code>BRIEFR_SCHEDULER_ENABLED</code>, <code>BRIEFR_RATE_LIMIT_STORE=db</code> for multi-worker, <code>BRIEFR_SETTINGS_KEY</code> for encrypted settings."},
            {"q": "How do API-only workers deploy?", "a": "Multiple uvicorn instances behind nginx with <code>BRIEFR_SCHEDULER_ENABLED=0</code>; exactly one scheduler owner with <code>=1</code>. Shared DB rate-limit store mandatory for consistent auth/IOC limits."},
            {"q": "What is log rotation?", "a": "Deploy artifacts include logrotate configs for structured JSON logs\u2014journald-friendly stderr from uvicorn."},
            {"q": "How is Postgres sized?", "a": "No official sizing envelope published; architecture targets small VPS\u2014CPU embeddings, single worker, bounded pool. Operators monitor admin Resources page and host disk I/O charts."},
            {"q": "What license applies?", "a": "Apache 2.0\u2014free for personal, commercial, and self-hosted use with attribution. SPDX headers in source trees."},
            {"q": "How do intel snapshots help DR?", "a": "Export/import bundles for allowlisted intel tables\u2014versioned manifest, verify script, documented in OPERATIONS.md. Complements pg_dump backups, not a replacement."},
            {"q": "What production warnings fire at startup?", "a": "Posture self-check logs per unsafe flag when <code>BRIEFR_ENV=production</code>\u2014rate limits off, insecure cookies, tokenless wallboard. Surfaced again in Admin Security panel."},
            {"q": "How is frontend released?", "a": "<code>npm run build</code> produces <code>dist/</code> copied to nginx root on deploy. Vite dev server proxies <code>/api</code> only for development."},
            {"q": "What about Playwright smoke?", "a": "Gated behind <code>PLAYWRIGHT_SMOKE=1</code> in verify-local full mode. Seeds SQLite and starts uvicorn + preview for UI smoke\u2014optional locally."},
            {"q": "How do deploy scripts stay safe?", "a": "Additive compatibility promise in ROADMAP/OPERATIONS\u2014<code>deploy/</code> scripts run on live production boxes; changes must not break existing operator paths."},
            {"q": "What would you check after a failed deploy?", "a": "Alembic version, health endpoint backend kind, scheduler owner flag, nginx proxy, JWT/auth login, feed row count, and application logs for migration or pool errors."},
        ],
    },
    {
        "slug": "iv-product-behavioral",
        "page_id": "iv-product-behavioral",
        "chapter_num": "Interview \u00b7 11",
        "title": "Product, behavioral & solo owner",
        "dek": "Roadmap judgment, trade-offs, and maintainer narrative in first person.",
        "prev": ("iv-devops-deploy.html", "DevOps & deploy"),
        "next": ("glossary.html", "Glossary"),
        "questions": [
            {"q": "Why build BRIEFR as a solo maintainer project?", "a": "I wanted analyst-grade CVE triage without SIEM cost or SaaS data residency concerns. A monolith with honest self-host docs matches how small teams actually deploy\u2014one Postgres, one operator, incremental flags instead of microservice sprawl."},
            {"q": "How do you prioritize the roadmap?", "a": "<code>docs/PRODUCT_STATUS.md</code> and <code>docs/planning/SPRINT_2026-07.md</code> drive truth. I ship operator pain first\u2014auth hardening, scheduler honesty, feed performance\u2014before greenfield features like full platform compose."},
            {"q": "Tell me about a hard technical trade-off you made.", "a": "I kept APScheduler in-process instead of jumping to Celery everywhere. Procrastinate is optional for a narrow durable queue. That trades theoretical scale for operability\u2014one lock map, one admin Scheduler page, predictable failures."},
            {"q": "How do you handle docs vs code drift?", "a": "PRODUCT_STATUS wins over README snapshots. I update SYSTEM_DESIGN and API_REFERENCE in the same PR as behavior changes. Corpus drift check in admin compares generated security architecture to committed files."},
            {"q": "Describe a production incident mindset you encoded.", "a": "RCA-first: reproduce, trace end-to-end, fix the class of bug, add a regression test. Example: FE refresh dedupe\u2014concurrent 401s could revoke all sessions; shared in-flight refresh fixed the structural race, not just retry logic."},
            {"q": "Why Apache 2.0?", "a": "Maximum adoption for defenders who cannot ship GPL contagion into commercial SOCs. Clear NOTICE attribution; aligns with SigmaHQ and ecosystem tooling expectations."},
            {"q": "How do you say no to features?", "a": "STIX export excluded from current loop, light theme removed, snooze removed, Investigation Score removed\u2014documented non-goals. I prefer deleting misleading UI over maintaining half-honest paths."},
            {"q": "What is your testing philosophy?", "a": "Default SQLite pytest for speed; Postgres path before merging db/ changes. verify-local as merge gate. Playwright smoke optional. Tests assert behavior operators see\u2014job lock maps, EPSS skip, Sigma index read path."},
            {"q": "How do you design for self-hosters with no API keys?", "a": "Core CVE feed, RSS, and search work offline from public feeds. Empty states explain missing VT/GreyNoise keys without looking broken. Keys enhance; they do not gate login."},
            {"q": "Tell me about UX debt you paid down.", "a": "Forge honesty PRs: no fake 'ranked for your stack', real EmptyState on sparse ATT&amp;CK matrix, community-Sigma-first Detect. I treat analyst trust as a feature\u2014wrong detection is worse than no detection."},
            {"q": "How do you manage LLM cost risk?", "a": "Router failover, pacing headroom, empty-payload skip, ai_operations metering without storing prompts. LLM defaults off for detection context; deterministic Nuclei path default on."},
            {"q": "What would you do differently starting over?", "a": "I might stamp Postgres-only earlier\u2014but SQLite test fallback still saves CI minutes. I'd also centralize model catalog from day one; we recovered from stale OpenRouter IDs with SSOT in <code>model_catalog.py</code>."},
            {"q": "How do you onboard a new contributor quickly?", "a": "CLAUDE.md rulebook, HANDOVER newest-first, graphify/study-guide for architecture. Danger zones call out scheduler lock strings, migration forward-only, and request-path heavy work prohibition."},
            {"q": "Describe coordinating UI and backend changes.", "a": "ADR-002 scoring shipped API-first\u2014frontend displays <code>/risk</code> only. Drawer bundle reduced chatty fetches. I resist duplicating business logic in React; it always drifts."},
            {"q": "How do you handle security findings?", "a": "Fail closed in production: JWT required, admin key removed, SSRF blocks expanded, session revalidation. Security posture page gives analysts read-only transparency without duplicating admin corpus editing."},
            {"q": "What metric would you track if you had more time?", "a": "Time-to-triage for stack-matched KEV CVEs\u2014proxy via feed sort + OP accuracy feedback. Today we expose operational signals (backlog notifications, feed health) more than product analytics."},
            {"q": "Why dark terminal aesthetic?", "a": "Analysts live in terminals and SOC walls; light mode was noise. Tokens and Radix gave accessibility without Material blandness. Density-first\u2014no hero marketing columns."},
            {"q": "How do you decide when to add Procrastinate vs APScheduler?", "a": "Durable when failure is expensive and retry semantics matter\u2014stack backfill, LLM product extraction. Cron ingest stays APScheduler with locks\u2014simpler mental model for operators."},
            {"q": "Where is BRIEFR headed next?", "a": "Durability tail (PR-R series), formal resource benchmarking, detection composer expansion, and honest platform compose\u2014while keeping single-server deploy the default story."},
        ],
    },
]
