"""TM-4: architecture graph loader + read-time attack-surface / node-context
merges over it (spec §5.2 System Architecture, §5.3 Trust Boundaries, §5.9
attack surface, §8 TM-4).

`graphs/architecture.json` (generated by scripts/generate_security_corpus.py,
committed under security_architecture/corpus/graphs/) carries only code
facts -- nodes (components/jobs/tables, exactly the ids already emitted in
components.yaml/scheduler_jobs.yaml/db_tables.yaml) and component->table
"references_table" edges. It does NOT carry attack-surface counts: those
depend on curated control->endpoint linkage (controls.yaml's related_apis
glob patterns), which is judgment, not a code fact -- so attack surface is
computed here at read time by joining the generated endpoint inventory
against the curated controls list, same "generated vs curated" split the
rest of the corpus already follows (spec §4.1). This is a one-pass glob
match over data already loaded by corpus_loader.get_corpus() -- no new SQL,
no scoring, counts only (spec §8 TM-4: "counts, not scores").

Copyright © 2026 Sai Harsha Vardhan
SPDX-License-Identifier: BUSL-1.1
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

GRAPH_PATH = Path(__file__).resolve().parent / "corpus" / "graphs" / "architecture.json"


class ArchitectureGraphError(ValueError):
    """graphs/architecture.json is missing or malformed."""


_caches: dict[Path, tuple[float, dict[str, Any]]] = {}


def get_architecture_graph(path: Path | None = None) -> dict[str, Any]:
    """Cached load of the generated architecture graph, invalidated on
    mtime change (same pattern as corpus_loader.get_corpus). Keyed by
    resolved path -- a global single-slot cache would pollute across calls
    with different `path` values (tests routinely pass a scratch path)."""
    p = (path or GRAPH_PATH).resolve()
    if not p.exists():
        raise ArchitectureGraphError(
            f"Missing {p} -- run `python scripts/generate_security_corpus.py`"
        )
    mtime = p.stat().st_mtime
    if p not in _caches or _caches[p][0] != mtime:
        with open(p, encoding="utf-8") as f:
            _caches[p] = (mtime, json.load(f))
    return _caches[p][1]


def _endpoint_matches_pattern(path: str, pattern: str) -> bool:
    """A control's `related_apis` entry is either an exact path, `*`
    (matches everything), or a `<prefix>/*` glob (matches the prefix itself
    and anything nested under it) -- the only two shapes controls.yaml
    actually uses (spec has no richer glob grammar to honor)."""
    if pattern == "*":
        return True
    if pattern.endswith("/*"):
        prefix = pattern[:-2]
        return path == prefix or path.startswith(prefix + "/")
    return path == pattern


def linked_controls_for_endpoint(
    endpoint_path: str, controls: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    """Every curated control whose `related_apis` covers this endpoint
    path -- the "linked controls" half of "attack surface = endpoint
    inventory × linked controls"."""
    return [
        c for c in controls
        if any(_endpoint_matches_pattern(endpoint_path, p) for p in (c.get("related_apis") or []))
    ]


def build_attack_surface(corpus: dict[str, Any]) -> dict[str, Any]:
    """Spec §8 TM-4: 'Attack surface = generated endpoint inventory × linked
    controls (counts, not scores)'. Every endpoint row carries its own
    linked-control count/ids so the total is never an opaque number --
    drilling into any row shows exactly which controls covered it, or that
    none did (Unreviewed Endpoints)."""
    endpoints = list((corpus.get("api_inventory") or {}).get("endpoints") or [])
    controls = list((corpus.get("controls") or {}).get("controls") or [])

    rows = []
    reviewed = 0
    for e in endpoints:
        linked = linked_controls_for_endpoint(e["path"], controls)
        if linked:
            reviewed += 1
        rows.append({
            **e,
            "linked_control_count": len(linked),
            "linked_control_ids": [c["id"] for c in linked],
        })

    return {
        "total_endpoints": len(rows),
        "reviewed_endpoints": reviewed,
        "unreviewed_endpoints": len(rows) - reviewed,
        "endpoints": rows,
    }


def build_node_context(
    node_id: str, corpus: dict[str, Any], graph: dict[str, Any]
) -> dict[str, Any] | None:
    """Context-rail payload for a selected architecture-graph node (spec
    §5.2 node selection panel, §8 TM-4: 'node selection populates the
    context rail'). One read-time join over corpus data already loaded --
    component nodes get endpoints + linked controls + referenced tables;
    table nodes get the reverse (which components reference them); job
    nodes get just their own record (scheduler_jobs.yaml has no live
    linkage to derive further without inventing one)."""
    nodes_by_id = {n["id"]: n for n in graph["nodes"]}
    node = nodes_by_id.get(node_id)
    if node is None:
        return None

    outbound = [e for e in graph["edges"] if e["source"] == node_id]
    inbound = [e for e in graph["edges"] if e["target"] == node_id]
    result: dict[str, Any] = {
        **node,
        "outbound": outbound,
        "inbound": inbound,
    }

    if node["kind"] == "component":
        component = next(
            (c for c in corpus["components"]["components"] if c["id"] == node_id), None
        )
        endpoints = [
            e for e in corpus["api_inventory"]["endpoints"]
            if e.get("component_id") == node_id
        ]
        all_controls = corpus["controls"]["controls"]
        linked_controls: list[dict[str, Any]] = []
        seen_control_ids: set[str] = set()
        for e in endpoints:
            for c in linked_controls_for_endpoint(e["path"], all_controls):
                if c["id"] not in seen_control_ids:
                    seen_control_ids.add(c["id"])
                    linked_controls.append(c)
        result.update({
            "summary": component.get("summary") if component else None,
            "owner": component.get("owner") if component else None,
            "endpoints": endpoints,
            "controls": linked_controls,
            "tables": [nodes_by_id[e["target"]] for e in outbound if e["target"] in nodes_by_id],
        })
    elif node["kind"] == "table":
        result["referenced_by"] = [
            nodes_by_id[e["source"]] for e in inbound if e["source"] in nodes_by_id
        ]
    elif node["kind"] in ("job", "core"):
        result["tables"] = [
            nodes_by_id[e["target"]]
            for e in outbound
            if e.get("kind") == "references_table" and e["target"] in nodes_by_id
        ]
        result["externals"] = [
            nodes_by_id[e["target"]]
            for e in outbound
            if e.get("kind") == "fetches_external" and e["target"] in nodes_by_id
        ]
    elif node["kind"] == "external":
        result["fetched_by"] = [
            nodes_by_id[e["source"]] for e in inbound if e["source"] in nodes_by_id
        ]

    return result
