/**
 * Shared jsPDF layout constants + helpers used by pdfReport.js and
 * investigationPdf.js. exportXlsx.js uses write-excel-file; CSV stays in exportCsv.js.
 * its own color/date handling — reviewed side-by-side and found no genuine
 * duplication with the PDF files worth extracting.
 */
export const BRAND = '#e85533'
export const PAGE_W = 210
export const MARGIN = 15
export const CONTENT_BOTTOM = 262
export const FOOTER_Y = 285
export const FONT_BODY = 'helvetica'
export const FONT_MONO = 'courier'
export const FOOTER_COPYRIGHT = '© 2026 BRIEFR · Generated by BRIEFR · Apache-2.0'
/** Public marketing site — not the private prod portal hostname. */
export const PUBLIC_SITE_URL = 'https://projectjupiter.in'

export function hexToRgb(hex) {
  const h = hex.replace('#', '')
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ]
}
