import { fetchAiSummary } from '../api.js'
import { sanitizePdfText } from './pdfText.js'

/**
 * Load executive summary for PDF export only (called from download handlers).
 */
export async function loadPdfExecutiveSummary({
  cves = [],
  iocs = [],
  actors = [],
  investigationDuration = 1,
}) {
  try {
    return await fetchAiSummary({
      cves,
      iocs,
      actors,
      investigationDuration,
    })
  } catch {
    return null
  }
}

const SOURCE_LABELS = {
  groq: 'Groq',
  gemini: 'Google Gemini',
  cerebras: 'Cerebras',
  openrouter: 'OpenRouter',
  template: 'BRIEFR template',
}

export function aiFooterNoteForSource(source) {
  const label = SOURCE_LABELS[source]
  if (!label) return null
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  return `Executive summary generated by ${label} — ${today}`
}

export function formatExecutiveSummaryBody(summaryData) {
  if (!summaryData?.executive_summary) {
    return 'Executive summary unavailable.'
  }
  const parts = [summaryData.executive_summary]
  const findings = summaryData.key_findings
  if (Array.isArray(findings) && findings.length) {
    parts.push('\n\nKey findings:\n' + findings.map(f => `• ${f}`).join('\n'))
  }
  return sanitizePdfText(parts.join(''))
}
