import { fetchAiSummary } from '../api.js'

/**
 * Load executive summary for PDF export only (called from download handlers).
 */
export async function loadPdfExecutiveSummary({
  cves = [],
  iocs = [],
  actors = [],
  investigationDuration = 1,
}) {
  try {
    return await fetchAiSummary({
      cves,
      iocs,
      actors,
      investigationDuration,
    })
  } catch {
    return null
  }
}

export function isAiAssistedSource(source) {
  return source === 'groq' || source === 'anthropic'
}

export function aiFooterNoteForSource(source) {
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  if (source === 'groq') {
    return `Executive summary generated by Groq / Llama 3.1 8B Instant — ${today}`
  }
  if (source === 'anthropic') {
    return `Executive summary generated by Anthropic / Claude Haiku — ${today}`
  }
  if (source === 'template') {
    return `Executive summary generated by BRIEFR template — ${today}`
  }
  return null
}

export function formatExecutiveSummaryBody(summaryData) {
  if (!summaryData?.executive_summary) {
    return 'Executive summary unavailable.'
  }
  const parts = [summaryData.executive_summary]
  const findings = summaryData.key_findings
  if (Array.isArray(findings) && findings.length) {
    parts.push('\n\nKey findings:\n' + findings.map(f => `• ${f}`).join('\n'))
  }
  return parts.join('')
}
